[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
description = "ORM-like API MongoDB for Rust"
edition = "2018"
keywords = ["mongodb", "mongo", "nosql", "database", "orm"]
license = "MIT OR Apache-2.0"
name = "mango-orm"
readme = "README.md"
repository = "https://github.com/kebasyaty/mango-orm"
version = "0.1.0-pre-alpha.2"

[dependencies]

[dependencies.mongodb]
default-features = false
features = ["tokio-runtime"]
version = "1.1.0"

[dev-dependencies]
tokio = "0.2.22"
