[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
description = "ORM-like API MongoDB for Rust"
edition = "2018"
keywords = ["mongodb", "mongo", "nosql", "database", "orm"]
license = "MIT OR Apache-2.0"
name = "mango-orm"
readme = "README.md"
repository = "https://github.com/kebasyaty/mango-orm"
version = "0.1.0-pre-alpha.8"

[dependencies]
async-mutex = "1.4.0"
chrono = "0.4.15"
futures = "0.3.5"
lazy_static = "1.4.0"
regex = "1.3.9"

[dependencies.mongodb]
default-features = false
features = ["tokio-runtime"]
version = "1.1.1"

[dependencies.tokio]
default-features = false
features = ["rt-threaded", "macros"]
version = "0.2.22"

[dependencies.serde]
features = ["derive"]
version = "1.0.115"
