[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing and defining dependencies for development."
edition = "2021"
name = "test-drive"
version = "0.1.0"

[dependencies]
chrono = "0.4.22"
green-barrel = {path = "../green-barrel"}
lazy_static = "1.4.0"
metamorphose = {path = "../metamorphose"}
rand = "0.8.5"
regex = "1.6.0"
rust-argon2 = "1.0.0"
serde_json = "1.0.87"
validator = "0.16.0"

[dependencies.mongodb]
default-features = false
features = ["sync", "bson-chrono-0_4"]
version = "2.3.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.147"
