[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing and defining dependencies for development."
edition = "2018"
name = "test-drive"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
lazy_static = "1.4.0"
mango-orm = {path = "../mango-orm"}
metamorphose = {path = "../metamorphose"}
rand = "0.8.5"
regex = "1.5.6"
rust-argon2 = "1.0.0"
serde_json = "1.0.81"
validator = "0.15.0"

[dependencies.mongodb]
default-features = false
features = ["sync"]
version = "1.2.5"

[dependencies.serde]
features = ["derive"]
version = "1.0.137"
