[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing and defining dependencies for development."
edition = "2018"
name = "test-drive"
version = "0.1.0"

[dependencies]
chrono = "0.4"
# mango-orm = "0.4"
# metamorphose = "0.2"
lazy_static = "1.0"
rand = "0.7"
regex = "1.0"
rust-argon2 = "0.8"
serde_json = "1.0"
validator = "0.11"

mango-orm = {path = "../mango-orm"}
metamorphose = {path = "../metamorphose"}

[dependencies.mongodb]
default-features = false
features = ["sync"]
version = "1.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
