[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing Mango-ORM"
edition = "2018"
name = "test-drive"
version = "0.1.0"

[dependencies]
async-trait = "0.1.40"

mango-orm = {path = "../mango-orm"}

[dependencies.mongodb]
default-features = false
features = ["tokio-runtime"]
version = "1.1.1"

[dependencies.tokio]
default-features = false
features = ["full"]
version = "0.2.22"

[dependencies.serde]
features = ["derive"]
version = "1.0.115"
