[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
description = "For manual testing Mango-ORM"
edition = "2018"
name = "test-drive"
version = "0.1.0"

[dependencies]
serde_json = "1.0.57"

mango-orm = {path = "../mango-orm"}
