[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing and defining dependencies for development."
edition = "2021"
name = "test-drive"
version = "0.1.0"

[dependencies]
chrono = "0.4.23"
confy = "0.5.1"
green-barrel = {path = "../green-barrel"}
metamorphose = {path = "../metamorphose"}
parking_lot = "0.12.1"
rand = "0.8.5"
regex = "1.7.0"
rust-argon2 = "1.0.0"
serde_json = "1.0.89"
validator = "0.16.0"

[dependencies.mongodb]
default-features = false
features = ["sync", "bson-chrono-0_4"]
version = "2.3.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.148"
