[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing Mango-ORM"
edition = "2018"
name = "test-drive"
version = "0.1.0"

[dependencies]

mango-orm = {path = "../mango-orm"}

[dependencies.mongodb]
default-features = false
features = ["tokio-runtime"]
version = "1.1.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.115"

[dev-dependencies]
tokio = {version = "0.2.22", features = ["rt-threaded", "macros"]}
