[package]
authors = ["kebasyaty <kebasyaty@gmail.com>"]
default-run = "test-drive"
description = "For manual testing and defining dependencies for development."
edition = "2018"
name = "test-drive"
version = "0.1.0"

[dependencies]
chrono = "0.4.19"
# metamorphose = "0.1.29-alpha.1"
lazy_static = "1.4"
rand = "0.7.3"
regex = "1.3.9"
rust-argon2 = "0.8.2"
serde_json = "1.0.57"
validator = "0.11.0"

mango-orm = {path = "../mango-orm"}
metamorphose = {path = "../metamorphose"}

[dependencies.mongodb]
default-features = false
features = ["sync"]
version = "1.1.1"

[dependencies.serde]
features = ["derive"]
version = "1.0.115"
