[package]
authors = ["Gennady Kostunin <kebasyaty@gmail.com>"]
description = "Macros collection for converting Structure to Model, for a mango-orm project."
edition = "2021"
homepage = "https://github.com/kebasyaty/mango-orm/tree/master/metamorphose"
keywords = ["mongodb", "mango", "mongo", "model", "macro"]
license = "MIT OR Apache-2.0"
name = "metamorphose"
readme = "README.md"
repository = "https://github.com/kebasyaty/mango-orm/tree/master/metamorphose"
version = "0.6.12"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.20"
regex = "1.5.6"
serde_json = "1.0.81"
syn = "1.0.98"

[dependencies.serde]
features = ["derive"]
version = "1.0.137"
